pretrained_model_name_or_path: '/data0/yclu/wonder3d/checkpoints/wonder3d_original_ckpt'
lora_output_dir: '/data0/yclu/wonder3d/checkpoints/wonder3d_exp09I_ckpt_10000_epochs'
revision: null
validation_dataset:
  root_dir: "./example_images" # the folder path stores testing images
  num_views: 7
  bg_color: 'white'
  img_wh: [256, 256]
  num_validation_samples: 1000
  crop_size: 192
  filepaths:   # the test image names. leave it empty, test all images in the folder

save_dir: '/input/yclu/wonder3d/outputs/debug/mv_results'

pred_type: 'rgb'
seed: 42
validation_batch_size: 1
dataloader_num_workers: 32
local_rank: -1
load_lora: true

pipe_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  num_views: 7

validation_guidance_scales: [3.0]
pipe_validation_kwargs:
  eta: 1.0
validation_grid_nrow: 7

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  projection_class_embeddings_input_dim: 14  
  num_views: 7
  sample_size: 32
  zero_init_conv_in: false
  zero_init_camera_projection: false
  cd_attention_last: false
  cd_attention_mid: false
  multiview_attention: true
  sparse_mv_attention: false
  mvcd_attention: false  

num_views: 7
camera_embedding_type: 'e_de_da_sincos'

enable_xformers_memory_efficient_attention: true
lora_alpha: 32
rank: 32
cam_type: 'persp' # 'persp' or 'ortho'
pixel_controller: true